# Series와 DataFrame의 차이는?
### 기본적으로 시리즈는 1차원 배열, 데이터프레임은 2차원 배열 혹은 행과 열이 있는 2차원 데이터 구조이다.

In [6]:
# 데이터프레임 만들기 기초

import pandas as pd

table_data = {"year" : [2015,2016,2017,2018,2018],
              "nation" : ['ko','ko','us','ja','ch'],
              "customer_number" : [200,250,300,250,400]}
table_data

{'year': [2015, 2016, 2017, 2018, 2018],
 'nation': ['ko', 'ko', 'us', 'ja', 'ch'],
 'customer_number': [200, 250, 300, 250, 400]}

In [11]:
df = pd.DataFrame(table_data) # Dataframe 생성
df

year nation  customer_number
0  2015     ko              200
1  2016     ko              250
2  2017     us              300
3  2018     ja              250
4  2018     ch              400

In [18]:
df = pd.DataFrame(data=table_data, columns=['nation', 'year','customer_number']) # 이런 식으로 칼럼 순서를 바꿀 수 있다
df # 굳이 df에 할당하는 이유는 없다~~ df 선언 안해도 잘만 나옴
# 그리고 pd.DataFrame(table_data, columns=['nation', 'year','customer_number'])

# pd.DataFrame(table_data, columns=['nation', 'year','customer_number']) << 이렇게 표시해도 똑같이 나옴

nation  year  customer_number
0     ko  2015              200
1     ko  2016              250
2     us  2017              300
3     ja  2018              250
4     ch  2018              400

In [ ]:
# Series 만들기 

s1 = pd.Series([10,20,30,40,50])
s1

In [21]:
# Numpy 기초
import numpy as np # 사실 as 뒤에 아무거나 붙여도 되는 건 함정~

data1 = [1,2,3,4,5,6.3,7,8,10]
a1 = np.array(data1)
a1

# 정수형, 실수형 데이터의 차이점을 한 번 살펴보자~

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6.3,  7. ,  8. , 10. ])

In [36]:
data2 = [[1,2,3],[2,3,4],[3,4,5]]
a2 = np.array(data2)
a2
# data2

# data2와 a2를 출력했을 때의 차이가 뭔가?

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [37]:
data2

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]

In [43]:
a1.reshape(1,-1) # 1행으로 모양 바꾸기
a1.reshape(3,3) # 3행으로 모양 바꾸기
# a1.reshape(4,4) # 빈 부분이 자동적으로 채워지진 않아서 에러 발생

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6.3],
       [ 7. ,  8. , 10. ]])

In [45]:
a1 # sort함수처럼 영구적으로 변형시키지는 않음

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6.3,  7. ,  8. , 10. ])

In [49]:
a1.reshape(3,3).shape
# shape은 모양이 어떻게 생겼나 살펴 볼 수 있음
# (행 갯수 , 열 갯수) 라고 이해하면 될 듯
# a1.shape

(3, 3)

In [54]:
a = range(2,11,2)
np.array(a)
# 이런 식으로 두 줄로 표현 할 수도 있지만

array([ 2,  4,  6,  8, 10])

In [61]:
np.arange(2,11,2) 
# np를 활용해 한줄로 표현 할 수도 있음.
# 단, range가 아닌 arange라는 것을 기억할 것

array([ 2,  4,  6,  8, 10])

In [63]:
np.linspace(1,10,5) # 1에서 10까지 5등분하여 나타내기 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
# 데이터 형이 문자 일 때, 실수로 변환 시
data = ["1","323.53","555","345.331"]
str_data = np.array(data)
float_data = str_data.astype(float)
float_data

array([  1.   , 323.53 , 555.   , 345.331])

In [36]:
# int_data.astype(str) # 이거 이해가 안되는게 int_data 선언한 적이 없는데 왜 되는 거임??
int_data = float_data.astype(int)
# 이거 개 귀찮은데 한번에 바꿀 방법은 없나?
int_data

array([  1, 323, 555, 345])

In [28]:
np.array(data).astype(float)

array([  1.   , 323.53 , 555.   , 345.331])

# 통계 기초 연산
#####   평균, 표준편차, 분산, 최대값, 최소값

In [37]:
# int_data = array([  1, 323, 555, 345])

[int_data.mean(), int_data.std(), int_data.var(), int_data.max(), int_data.min()]

[306.0, 198.01262586006985, 39209.0, 555, 1]

# Array 연산과 행렬 연산
### 1) Array 연산

In [41]:
A, B = [0,1,2,3] , [3,30,2,15]
arr_A = np.array(A)
arr_B = np.array(B)

In [43]:
arr_A + arr_B

array([ 3, 31,  4, 18])

In [45]:
arr_A * arr_B

array([ 0, 30,  4, 45])

### 2) 행렬 연산
#### 행렬곱, 전치행렬, 역행렬, 행렬식

In [50]:
# 기본적으로 덧셈/뺄셈은 크기가 같으면 가능 (ex. [2x3] + [2x3] 인 경우)
mat_A = np.array(A).reshape(2,2) # 2x2크기로 맞춰줘야 곱셈을 할 수 있음!
mat_B = np.array(B).reshape(2,2)

In [52]:
mat_A.dot(mat_B)

array([[  2,  15],
       [ 12, 105]])

In [54]:
mat_B.dot(mat_A)
# 당연히 알겠지만 행렬에서는
# AB == BA 가 무조건 성립하지 않는다

array([[60, 93],
       [30, 47]])

In [56]:
# 혹은 이렇게 표현 할 수도 있다.
np.dot(mat_A,mat_B)

array([[  2,  15],
       [ 12, 105]])

In [58]:
np.dot(mat_B,mat_A)

array([[60, 93],
       [30, 47]])

# 전치 행렬의 특성
#### 전치 행렬 : 행렬을 좌표로 표현했을 때, 좌상단부터 우하단까지 y = -x 직선`(주 대각선)`이 있다고 생각하면, y = -x 대칭인 행렬
#### https://namu.wiki/w/%EC%A0%84%EC%B9%98%ED%96%89%EB%A0%AC
#### 주요 특성
1) 정사각 행렬에서만 전치 행렬이 존재하는 것은 아님
   예를 들어, a = [1,2,3]을 전치하면
    a' = [[1],[2],[3]] 이 된다.
   
2) 보통, 주어진 행렬을 전치 했을 때 계산이 가능한 경우를 보고 싶을 때 사용한다고 생각하면 될 것 같다.

In [61]:
# 전치 행렬 구하기
np.transpose(mat_A)

array([[0, 2],
       [1, 3]])

In [63]:
mat_A.transpose()

array([[0, 2],
       [1, 3]])

In [68]:
# 역행렬 구하기
inv_A = np.linalg.inv(mat_A)
inv_A

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [69]:
# 역행렬 잘 구해 졌는지 확인해보자
np.dot(mat_A,inv_A)

array([[1., 0.],
       [0., 1.]])

In [75]:
inv_B = np.linalg.inv(mat_B)
inv_B

array([[-1.        ,  2.        ],
       [ 0.13333333, -0.2       ]])

In [77]:
np.dot(inv_B,mat_B)

array([[1., 0.],
       [0., 1.]])

In [79]:
# determinant(행렬식) 구하기, ad-bc
np.linalg.det(mat_A)

-2.0

# 배열의 인덱싱과 슬라이싱

In [81]:
a1 = np.array([1,2,3,4,5,7,7])
a1

array([1, 2, 3, 4, 5, 7, 7])

In [84]:
a1[0] # 리스트에서 맨날 쓰던 거랑 똑같다

1

In [87]:
a1[:3]

array([1, 2, 3])

In [88]:
a1[::-1]

array([7, 7, 5, 4, 3, 2, 1])

In [109]:
a = list(i for i in range(len(a1)))
a1[a] # 이렇게는 된다

array([1, 2, 3, 4, 5, 7, 7])

In [111]:
a1[1,2,3] # 이렇게는 안된다.

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [113]:
a1[[1,2,3]] # 대신 이렇게 하면 된다.

array([2, 3, 4])

In [116]:
a2 = [1,2,3,4,5]
a2[1]

2

In [119]:
a2 = np.array(a2) # 일반적인 리스트 상태일 때는 인덱스에 리스트를 넣는 것은 사용 불가임
a2[[1,2,3]]       # 반드시, np.array 이후 사용할 것

array([2, 3, 4])

In [194]:
a3 = np.arange(10,100,10)
a3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [195]:
a3 = a3.reshape(3,3)
a3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [196]:
a3[0,2] #a3[0][2] 와 같음

30

In [197]:
a3[0][2]

30

In [198]:
a3 + [1,2,3]

# 이건뭐야 대쳌ㅋㅋㅋㅋㅋ

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

In [199]:
a3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [201]:
a3[[1,2],[0,1]] # 여러 원소 가져오기

array([40, 80])

In [204]:
a3[:2] # 슬라이싱도 가능함

array([[10, 20, 30],
       [40, 50, 60]])

In [228]:
a4 = np.arange(15,160,16)
a4 
# array([ 15,  31,  47,  63,  79,  95, 111, 127, 143, 159])

a4[a4>100] # 이렇게 조건 식을 넣을 수 도 있음 

array([111, 127, 143, 159])

In [277]:
sort_a4 = a4.sort() # 이렇게 하면 안되고
sort_a4 = np.sort(a4) 
sort_a4[:3]

array([15, 31, 47])

In [241]:
minus_a4 = sort_a4[::-1] # 내림차 순으로 정렬
minus_a4 , sort_a4

(array([159, 143, 127, 111,  95,  79,  63,  47,  31,  15]),
 array([ 15,  31,  47,  63,  79,  95, 111, 127, 143, 159]))

In [267]:
a5 = [1,-52,23,123,54,156,-233,-5,0,215,45]
a5 += [3,]
len(a5)

12

In [278]:
a5 = np.array(a5).reshape(3,4)
a5

array([[   1,  -52,   23,  123],
       [  54,  156, -233,   -5],
       [   0,  215,   45,    3]])

In [296]:
sort_a5 = np.sort(a5) # 아무것도 안넣으면 axis= 1
a5, sort_a5 # 모든 행의 순서까지 sort


(array([[   1,  -52,   23,  123],
        [  54,  156, -233,   -5],
        [   0,  215,   45,    3]]),
 array([[ -52,    1,   23,  123],
        [-233,   -5,   54,  156],
        [   0,    3,   45,  215]]))

In [293]:
sort_a5 = np.sort(a5,axis = 0) 
a5, sort_a5 # 이거 도대체 나한테 왜이럼?

(array([[   1,  -52,   23,  123],
        [  54,  156, -233,   -5],
        [   0,  215,   45,    3]]),
 array([[   0,  -52, -233,   -5],
        [   1,  156,   23,    3],
        [  54,  215,   45,  123]]))

In [294]:
sort_a5 = np.sort(a5,axis = 1) 
a5, sort_a5
# axis 0을 기준으로 정렬하면, 세로로 보았을 때 작은 값부터 정렬되었음을 볼 수 있다.
# axis 1은 가로로 보았을 때 작은 값부터 정렬되어있다.

# https://for-data-science.tistory.com/8 [For Data Science:티스토리]

(array([[   1,  -52,   23,  123],
        [  54,  156, -233,   -5],
        [   0,  215,   45,    3]]),
 array([[ -52,    1,   23,  123],
        [-233,   -5,   54,  156],
        [   0,    3,   45,  215]]))

In [297]:
sort_a5 = np.sort(a5,axis = 2) 
sort_a5
# 현재 2차원으로 돼있어서, 0,1 까지 인덱스만 넣을 수 있음

AxisError: axis 2 is out of bounds for array of dimension 2

In [350]:
"""
여기서 부터 시작~~~
"""

import random
# a6 = [random.randrange(-100,100) for i in range(10)]
price = [-60, 80, 95, 30, -11, 61, 75, -76, 11, -22]
price = np.array(a6)

In [355]:
# a6 = [str(random.randrange(-100,100)) for i in range(10)]
name = ['-39', '-22', '79', '69', '7', '98', '44', '-52', '24', '-66']
name = np.array(name)
name

array(['-39', '-22', '79', '69', '7', '98', '44', '-52', '24', '-66'],
      dtype='<U3')

In [356]:
sort = np.argsort(price)  # price 순서 그대로 뒀을 때 이를 인덱스만으로 나타내면
sort                      # sort와 같은 형태로 표현 가능해진다.

array([7, 0, 9, 4, 8, 3, 5, 6, 1, 2], dtype=int64)

In [358]:
name[sort]

"""
여기까지~~
"""

'\n여기까지~~\n'

In [362]:
sort = np.argsort(price)[::-1]  # price 역순을 인덱스만 남기기
sort

array([2, 1, 6, 5, 3, 8, 4, 9, 0, 7], dtype=int64)

In [364]:
name[sort]

array(['79', '-22', '44', '98', '69', '24', '7', '-66', '-39', '-52'],
      dtype='<U3')

In [372]:
# 마지막이다...
A = np.arange(10,100,10)
A = A.reshape(3,3)
A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [388]:
A , A[2,1:], A[1][1:], A[:2,:2], A[1:] # 온갖 희한한 방법이 가능하다... 
# 개이상함...
A, A[1:][1:], A[:1][:1], A[:2][:2], A[0][2:]

(array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]),
 array([[70, 80, 90]]),
 array([[10, 20, 30]]),
 array([[10, 20, 30],
        [40, 50, 60]]),
 array([30]))